"""
Comprehensive NSE stock database (~500+ stocks).
Covers NIFTY 50, NIFTY Next 50, NIFTY Midcap 100, Smallcap, and popular stocks.
Used for local/offline search. Yahoo Finance search API covers anything beyond this.
"""

# (symbol_without_suffix, company_name)
NSE_STOCKS = [
    ("RELIANCE", "Reliance Industries"),
    ("TCS", "Tata Consultancy Services"),
    ("HDFCBANK", "HDFC Bank"),
    ("INFY", "Infosys"),
    ("ICICIBANK", "ICICI Bank"),
    ("HINDUNILVR", "Hindustan Unilever"),
    ("SBIN", "State Bank of India"),
    ("BHARTIARTL", "Bharti Airtel"),
    ("ITC", "ITC Limited"),
    ("KOTAKBANK", "Kotak Mahindra Bank"),
    ("LT", "Larsen & Toubro"),
    ("AXISBANK", "Axis Bank"),
    ("WIPRO", "Wipro"),
    ("HCLTECH", "HCL Technologies"),
    ("TATAMOTORS", "Tata Motors"),
    ("SUNPHARMA", "Sun Pharmaceutical"),
    ("MARUTI", "Maruti Suzuki"),
    ("TITAN", "Titan Company"),
    ("BAJFINANCE", "Bajaj Finance"),
    ("ADANIENT", "Adani Enterprises"),
    ("ASIANPAINT", "Asian Paints"),
    ("BAJAJFINSV", "Bajaj Finserv"),
    ("NESTLEIND", "Nestle India"),
    ("ULTRACEMCO", "UltraTech Cement"),
    ("JSWSTEEL", "JSW Steel"),
    ("NTPC", "NTPC Limited"),
    ("M&M", "Mahindra & Mahindra"),
    ("POWERGRID", "Power Grid Corporation"),
    ("ONGC", "Oil & Natural Gas Corporation"),
    ("TECHM", "Tech Mahindra"),
    ("TATASTEEL", "Tata Steel"),
    ("COALINDIA", "Coal India"),
    ("HINDALCO", "Hindalco Industries"),
    ("INDUSINDBK", "IndusInd Bank"),
    ("DIVISLAB", "Divi's Laboratories"),
    ("GRASIM", "Grasim Industries"),
    ("CIPLA", "Cipla"),
    ("DRREDDY", "Dr Reddy's Laboratories"),
    ("APOLLOHOSP", "Apollo Hospitals"),
    ("EICHERMOT", "Eicher Motors"),
    ("BRITANNIA", "Britannia Industries"),
    ("HEROMOTOCO", "Hero MotoCorp"),
    ("TATACONSUM", "Tata Consumer Products"),
    ("BEL", "Bharat Electronics"),
    ("SBILIFE", "SBI Life Insurance"),
    ("HDFCLIFE", "HDFC Life Insurance"),
    ("ADANIPORTS", "Adani Ports & SEZ"),
    ("BAJAJ-AUTO", "Bajaj Auto"),
    ("SHRIRAMFIN", "Shriram Finance"),
    ("DMART", "Avenue Supermarts (DMart)"),
    ("ABB", "ABB India"),
    ("ACC", "ACC Limited"),
    ("AMBUJACEM", "Ambuja Cements"),
    ("BANKBARODA", "Bank of Baroda"),
    ("BERGEPAINT", "Berger Paints"),
    ("BOSCHLTD", "Bosch"),
    ("CANBK", "Canara Bank"),
    ("CHOLAFIN", "Cholamandalam Finance"),
    ("COLPAL", "Colgate Palmolive"),
    ("CONCOR", "Container Corporation"),
    ("DABUR", "Dabur India"),
    ("DLF", "DLF Limited"),
    ("GAIL", "GAIL India"),
    ("GODREJCP", "Godrej Consumer Products"),
    ("HAVELLS", "Havells India"),
    ("ICICIPRULI", "ICICI Prudential Life"),
    ("IDFCFIRSTB", "IDFC First Bank"),
    ("INDHOTEL", "Indian Hotels"),
    ("INDIGO", "InterGlobe Aviation (IndiGo)"),
    ("IOC", "Indian Oil Corporation"),
    ("IRCTC", "IRCTC"),
    ("JINDALSTEL", "Jindal Steel & Power"),
    ("JIOFIN", "Jio Financial Services"),
    ("LICI", "Life Insurance Corporation"),
    ("LUPIN", "Lupin"),
    ("MAXHEALTH", "Max Healthcare"),
    ("MOTHERSON", "Motherson Sumi Wiring"),
    ("MUTHOOTFIN", "Muthoot Finance"),
    ("NAUKRI", "Info Edge (Naukri)"),
    ("NHPC", "NHPC Limited"),
    ("OBEROIRLTY", "Oberoi Realty"),
    ("OFSS", "Oracle Financial Services"),
    ("PAYTM", "One97 Communications (Paytm)"),
    ("PEL", "Piramal Enterprises"),
    ("PERSISTENT", "Persistent Systems"),
    ("PETRONET", "Petronet LNG"),
    ("PIDILITIND", "Pidilite Industries"),
    ("PNB", "Punjab National Bank"),
    ("POLYCAB", "Polycab India"),
    ("RECLTD", "REC Limited"),
    ("SAIL", "Steel Authority of India"),
    ("SIEMENS", "Siemens"),
    ("SRF", "SRF Limited"),
    ("TATAELXSI", "Tata Elxsi"),
    ("TATAPOWER", "Tata Power"),
    ("TRENT", "Trent Limited"),
    ("VBL", "Varun Beverages"),
    ("VEDL", "Vedanta"),
    ("ZOMATO", "Zomato"),
    ("ZYDUSLIFE", "Zydus Lifesciences"),
    ("TORNTPHARM", "Torrent Pharmaceuticals"),
    ("ADANIGREEN", "Adani Green Energy"),
    ("ADANIPOWER", "Adani Power"),
    ("ATGL", "Adani Total Gas"),
    ("AUROPHARMA", "Aurobindo Pharma"),
    ("BANDHANBNK", "Bandhan Bank"),
    ("BATAINDIA", "Bata India"),
    ("BHEL", "Bharat Heavy Electricals"),
    ("BIOCON", "Biocon"),
    ("BPCL", "Bharat Petroleum"),
    ("CANFINHOME", "Can Fin Homes"),
    ("CGPOWER", "CG Power & Industrial"),
    ("COFORGE", "Coforge"),
    ("CUMMINSIND", "Cummins India"),
    ("DEEPAKNTR", "Deepak Nitrite"),
    ("DIXON", "Dixon Technologies"),
    ("ESCORTS", "Escorts Kubota"),
    ("EXIDEIND", "Exide Industries"),
    ("FEDERALBNK", "Federal Bank"),
    ("FORTIS", "Fortis Healthcare"),
    ("GMRINFRA", "GMR Airports Infrastructure"),
    ("GNFC", "Gujarat Narmada Valley"),
    ("GODREJPROP", "Godrej Properties"),
    ("HAL", "Hindustan Aeronautics"),
    ("HDFCAMC", "HDFC AMC"),
    ("HINDZINC", "Hindustan Zinc"),
    ("IPCALAB", "IPCA Laboratories"),
    ("IRFC", "Indian Railway Finance"),
    ("IEX", "Indian Energy Exchange"),
    ("INDIAMART", "IndiaMART InterMESH"),
    ("JKCEMENT", "JK Cement"),
    ("JUBLFOOD", "Jubilant Foodworks"),
    ("KALYANKJIL", "Kalyan Jewellers"),
    ("KEI", "KEI Industries"),
    ("KPITTECH", "KPIT Technologies"),
    ("L&TFH", "L&T Finance"),
    ("LICHSGFIN", "LIC Housing Finance"),
    ("LTTS", "L&T Technology Services"),
    ("MANAPPURAM", "Manappuram Finance"),
    ("MARICO", "Marico"),
    ("MFSL", "Max Financial Services"),
    ("MGL", "Mahanagar Gas"),
    ("LTIM", "LTIMindtree"),
    ("MPHASIS", "Mphasis"),
    ("NAM-INDIA", "Nippon Life India AMC"),
    ("NATIONALUM", "National Aluminium"),
    ("NAVINFLUOR", "Navin Fluorine"),
    ("NMDC", "NMDC"),
    ("PAGEIND", "Page Industries"),
    ("PHOENIXLTD", "Phoenix Mills"),
    ("PIIND", "PI Industries"),
    ("PVRINOX", "PVR INOX"),
    ("RAIN", "Rain Industries"),
    ("RAMCOCEM", "Ramco Cements"),
    ("RBLBANK", "RBL Bank"),
    ("SBICARD", "SBI Cards"),
    ("SCHAEFFLER", "Schaeffler India"),
    ("SONACOMS", "Sona BLW Precision"),
    ("STARHEALTH", "Star Health Insurance"),
    ("SUNTV", "Sun TV Network"),
    ("SUPREMEIND", "Supreme Industries"),
    ("SYNGENE", "Syngene International"),
    ("TATACHEM", "Tata Chemicals"),
    ("TATACOMM", "Tata Communications"),
    ("TVSMOTOR", "TVS Motor Company"),
    ("UBL", "United Breweries"),
    ("UNIONBANK", "Union Bank of India"),
    ("UPL", "UPL Limited"),
    ("VOLTAS", "Voltas"),
    ("WHIRLPOOL", "Whirlpool of India"),
    ("YESBANK", "Yes Bank"),
    ("AARTIIND", "Aarti Industries"),
    ("ABCAPITAL", "Aditya Birla Capital"),
    ("ABFRL", "Aditya Birla Fashion"),
    ("AJANTPHARM", "Ajanta Pharma"),
    ("ALKEM", "Alkem Laboratories"),
    ("ALOKINDS", "Alok Industries"),
    ("AMARAJABAT", "Amara Raja Energy"),
    ("ANGELONE", "Angel One"),
    ("APLLTD", "APL Apollo Tubes"),
    ("ASHOKLEY", "Ashok Leyland"),
    ("ASTRAL", "Astral Limited"),
    ("ATUL", "Atul Limited"),
    ("AFFLE", "Affle India"),
    ("BALRAMCHIN", "Balrampur Chini"),
    ("BSOFT", "Birlasoft"),
    ("BSE", "BSE Limited"),
    ("CDSL", "Central Depository Services"),
    ("CENTRALBK", "Central Bank of India"),
    ("CHAMBLFERT", "Chambal Fertilizers"),
    ("CLEAN", "Clean Science & Technology"),
    ("COCHINSHIP", "Cochin Shipyard"),
    ("CROMPTON", "Crompton Greaves Consumer"),
    ("CUB", "City Union Bank"),
    ("CESC", "CESC Limited"),
    ("DALBHARAT", "Dalmia Bharat"),
    ("DELTACORP", "Delta Corp"),
    ("DEVYANI", "Devyani International"),
    ("EMAMILTD", "Emami"),
    ("ENDURANCE", "Endurance Technologies"),
    ("EQUITASBNK", "Equitas Small Finance Bank"),
    ("FACT", "Fertilisers & Chemicals Travancore"),
    ("FINCABLES", "Finolex Cables"),
    ("FLUOROCHEM", "Gujarat Fluorochemicals"),
    ("GLENMARK", "Glenmark Pharmaceuticals"),
    ("GLAXO", "GlaxoSmithKline Pharma"),
    ("GRANULES", "Granules India"),
    ("GRAPHITE", "Graphite India"),
    ("GRINDWELL", "Grindwell Norton"),
    ("GSPL", "Gujarat State Petronet"),
    ("GUJGASLTD", "Gujarat Gas"),
    ("HAPPSTMNDS", "Happiest Minds"),
    ("HFCL", "HFCL"),
    ("HONAUT", "Honeywell Automation"),
    ("HUDCO", "HUDCO"),
    ("ICICIGI", "ICICI Lombard General"),
    ("IDBI", "IDBI Bank"),
    ("IDEA", "Vodafone Idea"),
    ("INDIANB", "Indian Bank"),
    ("INDUSTOWER", "Indus Towers"),
    ("INTELLECT", "Intellect Design Arena"),
    ("IRCON", "Ircon International"),
    ("ITI", "ITI Limited"),
    ("J&KBANK", "Jammu & Kashmir Bank"),
    ("JBCHEPHARM", "JB Chemicals & Pharma"),
    ("JSWENERGY", "JSW Energy"),
    ("JSWINFRA", "JSW Infrastructure"),
    ("JUSTDIAL", "Just Dial"),
    ("KAJARIACER", "Kajaria Ceramics"),
    ("KANSAINER", "Kansai Nerolac Paints"),
    ("KEC", "KEC International"),
    ("KRBL", "KRBL"),
    ("LAURUSLABS", "Laurus Labs"),
    ("LALPATHLAB", "Dr Lal PathLabs"),
    ("LATENTVIEW", "Latent View Analytics"),
    ("LLOYDSME", "Lloyds Metals & Energy"),
    ("M&MFIN", "Mahindra & Mahindra Financial"),
    ("MAZAGONDOC", "Mazagon Dock Shipbuilders"),
    ("MCX", "Multi Commodity Exchange"),
    ("METROPOLIS", "Metropolis Healthcare"),
    ("MSUMI", "Motherson Sumi Systems"),
    ("NATCOPHARM", "Natco Pharma"),
    ("NBCC", "NBCC India"),
    ("NCC", "NCC Limited"),
    ("NYKAA", "FSN E-Commerce (Nykaa)"),
    ("OBOBC", "Union Bank of India"),
    ("OLECTRA", "Olectra Greentech"),
    ("PGHH", "Procter & Gamble Hygiene"),
    ("POLICYBZR", "PB Fintech (PolicyBazaar)"),
    ("POWERINDIA", "Hitachi Energy India"),
    ("PPLPHARMA", "Piramal Pharma"),
    ("PRESTIGE", "Prestige Estates"),
    ("PTC", "PTC India"),
    ("RADICO", "Radico Khaitan"),
    ("RVNL", "Rail Vikas Nigam"),
    ("RAJESHEXPO", "Rajesh Exports"),
    ("RALLIS", "Rallis India"),
    ("RAYMOND", "Raymond"),
    ("ROUTE", "Route Mobile"),
    ("SAPPHIRE", "Sapphire Foods"),
    ("SHREECEM", "Shree Cement"),
    ("SJVN", "SJVN Limited"),
    ("SUZLON", "Suzlon Energy"),
    ("SOLARINDS", "Solar Industries"),
    ("SONATSOFTW", "Sonata Software"),
    ("SUNDRMFAST", "Sundram Fasteners"),
    ("SWANENERGY", "Swan Energy"),
    ("SYMPHONY", "Symphony"),
    ("TATATECH", "Tata Technologies"),
    ("TIINDIA", "Tube Investments of India"),
    ("TIMKEN", "Timken India"),
    ("TORNTPOWER", "Torrent Power"),
    ("TRIDENT", "Trident Limited"),
    ("UJJIVANSFB", "Ujjivan Small Finance Bank"),
    ("UNOMINDA", "UNO Minda"),
    ("VIJAYA", "Vijaya Diagnostic Centre"),
    ("WOCKPHARMA", "Wockhardt"),
    ("ZEEL", "Zee Entertainment"),
    ("ZENSARTECH", "Zensar Technologies"),
    ("3MINDIA", "3M India"),
    ("AAVAS", "Aavas Financiers"),
    ("ABSLAMC", "Aditya Birla Sun Life AMC"),
    ("BORORENEW", "Borosil Renewables"),
    ("CARBORUNIV", "Carborundum Universal"),
    ("CHALET", "Chalet Hotels"),
    ("DATAPATTNS", "Data Patterns India"),
    ("DELHIVERY", "Delhivery"),
    ("ELGIEQUIP", "Elgi Equipments"),
    ("FIVESTAR", "Five-Star Business Finance"),
    ("GESHIP", "Great Eastern Shipping"),
    ("GPPL", "Gujarat Pipavav Port"),
    ("HINDPETRO", "Hindustan Petroleum"),
    ("IDFC", "IDFC Limited"),
    ("JKLAKSHMI", "JK Lakshmi Cement"),
    ("JSL", "Jindal Stainless"),
    ("KAYNES", "Kaynes Technology"),
    ("LXCHEM", "Laxmi Organic Industries"),
    ("MEDANTA", "Global Health (Medanta)"),
    ("MOTILALOFS", "Motilal Oswal Financial"),
    ("MSTCLTD", "MSTC Limited"),
    ("MULTICOMM", "Multi Commodity Exchange"),
    ("OIL", "Oil India"),
    ("POONAWALLA", "Poonawalla Fincorp"),
    ("RATNAMANI", "Ratnamani Metals"),
    ("RITES", "RITES Limited"),
    ("SANOFI", "Sanofi India"),
    ("SOBHA", "Sobha Limited"),
    ("SUMICHEM", "Sumitomo Chemical India"),
    ("TATAINVEST", "Tata Investment Corp"),
    ("THERMAX", "Thermax"),
    ("TRITURBINE", "Triveni Turbine"),
    ("UCOBANK", "UCO Bank"),
    ("VIKAS", "Vikas Lifecare"),
    ("ZFCVINDIA", "ZF Commercial Vehicle Control"),
    ("ADANIENSOL", "Adani Energy Solutions"),
    ("AWL", "Adani Wilmar"),
    ("HINDCOPPER", "Hindustan Copper"),
    ("MAZDOCK", "Mazagon Dock Shipbuilders"),
    ("BDL", "Bharat Dynamics"),
    ("GRSE", "Garden Reach Shipbuilders"),
    ("CAMS", "Computer Age Management Services"),
    ("NIACL", "New India Assurance"),
    ("GICRE", "General Insurance Corporation"),
    ("PNBHOUSING", "PNB Housing Finance"),
    ("MANINFRA", "Man Infraconstruction"),
    ("EIDPARRY", "EID Parry"),
    ("TTML", "Tata Teleservices"),
    ("GPIL", "Godawari Power & Ispat"),
    ("JYOTHYLAB", "Jyothy Labs"),
    ("PFIZER", "Pfizer"),
    ("ABBOTINDIA", "Abbott India"),
    ("MCDOWELL-N", "United Spirits"),
    ("SUNCLAYLTD", "Sundaram Clayton"),
    ("FINEORG", "Fine Organic Industries"),
    ("HATSUN", "Hatsun Agro Product"),
    ("TANLA", "Tanla Platforms"),
    ("STARCEMENT", "Star Cement"),
    ("RATEGAIN", "RateGain Travel Technologies"),
    ("CAMPUS", "Campus Activewear"),
    ("HAPPYFORGE", "Happy Forgings"),
    ("INOXWIND", "Inox Wind"),
    ("JAIBALAJI", "Jai Balaji Industries"),
    ("APARINDS", "Apar Industries"),
    ("SAGCEM", "Sagar Cements"),
    ("CYIENT", "Cyient"),
    ("MINDTREE", "LTIMindtree"),
    ("CERA", "Cera Sanitaryware"),
    ("GARFIBRES", "Garware Technical Fibres"),
    ("ALKYLAMINE", "Alkyl Amines Chemicals"),
    ("BALAMINES", "Balaji Amines"),
    ("NOCIL", "NOCIL"),
    ("SUDARSCHEM", "Sudarshan Chemical"),
    ("GALAXYSURF", "Galaxy Surfactants"),
    ("SUNTECK", "Sunteck Realty"),
    ("BRIGADE", "Brigade Enterprises"),
    ("MAHLIFE", "Mahindra Lifespace"),
    ("CARTRADE", "CarTrade Tech"),
    ("EASEMYTRIP", "Easy Trip Planners"),
    ("IDEAFORGE", "Ideaforge Technology"),
    ("RAILTEL", "RailTel Corporation"),
    ("FINPIPE", "Finolex Industries"),
    ("CENTURYTEX", "Century Textiles"),
    ("GUJALKALI", "Gujarat Alkalies"),
    ("DEEPAKFERT", "Deepak Fertilisers"),
    ("RCF", "Rashtriya Chemicals"),
    ("NFL", "National Fertilizers"),
    ("MMTC", "MMTC"),
    ("MOIL", "MOIL"),
    ("NLCINDIA", "NLC India"),
    ("POWERMECH", "Power Mech Projects"),
    ("ENGINERSIN", "Engineers India"),
    ("BEML", "BEML"),
    ("MIDHANI", "Mishra Dhatu Nigam"),
    ("MAHABANK", "Bank of Maharashtra"),
    ("IOB", "Indian Overseas Bank"),
    ("BANKINDIA", "Bank of India"),
    ("PSB", "Punjab & Sind Bank"),
    ("PFC", "Power Finance Corporation"),
    ("IREDA", "Indian Renewable Energy Dev Agency"),
    ("CADILAHC", "Zydus Cadila Healthcare"),
    ("GLAND", "Gland Pharma"),
    ("GSFC", "Gujarat State Fertilizers"),
    ("IIFL", "IIFL Finance"),
    ("MRF", "MRF Limited"),
    ("PATANJALI", "Patanjali Foods"),
    ("SUNDARMFIN", "Sundaram Finance"),
    ("ADANITRANS", "Adani Transmission"),
    ("AEGISCHEM", "Aegis Chemical"),
    ("AETHER", "Aether Industries"),
    ("AMBER", "Amber Enterprises"),
    ("ANANDRATHI", "Anand Rathi Wealth"),
    ("APLAPOLLO", "APL Apollo Tubes"),
    ("ASAHIINDIA", "Asahi India Glass"),
    ("CHEMCON", "Chemcon Speciality"),
    ("ELECTCAST", "Electrosteel Castings"),
    ("ELECON", "Elecon Engineering"),
    ("FSL", "FirstSource Solutions"),
    ("GOCOLORS", "Go Fashion"),
    ("HGS", "Hinduja Global Solutions"),
    ("HOMEFIRST", "Home First Finance"),
    ("JTEKTINDIA", "JTEKT India"),
    ("KFINTECH", "KFin Technologies"),
    ("MAPMYINDIA", "CE Info Systems"),
    ("MASTEK", "Mastek"),
    ("MAZAGONDOCK", "Mazagon Dock Shipbuilders"),
    ("POLYMED", "Poly Medicure"),
    ("PRINCEPIPE", "Prince Pipes & Fittings"),
    ("RAINBOW", "Rainbow Children's Medicare"),
    ("SWIGGY", "Swiggy"),
    ("UTIAMC", "UTI AMC"),
    ("VAIBHAVGBL", "Vaibhav Global"),
    ("WAAREEENER", "Waree Energies"),
    ("WELCORP", "Welspun Corp"),
    ("ZENTEC", "Zen Technologies"),
    ("KTKBANK", "Karnataka Bank"),
    ("KARURVYSYA", "Karur Vysya Bank"),
    ("TMBANK", "Tamilnad Mercantile Bank"),
    ("ESAFSFB", "ESAF Small Finance Bank"),
    ("BAJAJHLDNG", "Bajaj Holdings & Investment"),
    ("NUVAMA", "Nuvama Wealth Management"),
    ("APTUS", "Aptus Value Housing Finance"),
    ("JMFINANCIL", "JM Financial"),
    ("HCC", "Hindustan Construction Company"),
    ("GRINFRA", "G R Infraprojects"),
    ("KALPATPOWR", "Kalpataru Projects International"),
    ("PNCINFRA", "PNC Infratech"),
    ("NEWGEN", "Newgen Software Technologies"),
    ("EMUDHRA", "eMudhra"),
    ("BIRLASOFT", "Birlasoft"),
    ("NAZARA", "Nazara Technologies"),
    ("MEDPLUS", "MedPlus Health Services"),
    ("VEDANT", "Vedant Fashions"),
    ("ETHOS", "Ethos Limited"),
    ("SENCO", "Senco Gold"),
    ("BIKAJI", "Bikaji Foods International"),
    ("KIMS", "Krishna Institute of Medical Sciences"),
    ("NH", "Narayana Hrudayalaya"),
    ("THYROCARE", "Thyrocare Technologies"),
    ("ASTRAZEN", "AstraZeneca Pharma India"),
    ("ERIS", "Eris Lifesciences"),
    ("SUVEN", "Suven Pharmaceuticals"),
    ("AARTIDRUGS", "Aarti Drugs"),
    ("CASTROLIND", "Castrol India"),
    ("GILLETTE", "Gillette India"),
    ("CCL", "CCL Products India"),
    ("ADANIWILMAR", "Adani Wilmar"),
    ("HEIDELBERG", "HeidelbergCement India"),
    ("BIRLACORPN", "Birla Corporation"),
    ("ORIENTCEM", "Orient Cement"),
    ("BLUESTARCO", "Blue Star"),
    ("ORIENTELEC", "Orient Electric"),
    ("VGUARD", "V Guard Industries"),
    ("SKFINDIA", "SKF India"),
    ("SUPRAJIT", "Suprajit Engineering"),
    ("MAHINDCIE", "Mahindra CIE Automotive"),
    ("JINDALSAW", "Jindal Saw"),
    ("LEMONTREE", "Lemon Tree Hotels"),
    ("EIHOTEL", "EIH Limited"),
    ("NETWORK18", "Network18 Media"),
    ("TV18BRDCST", "TV18 Broadcast"),
    ("CHAMBALFER", "Chambal Fertilisers"),
    ("SHARDACROP", "Sharda Cropchem"),
    ("BAYER", "Bayer CropScience"),
    ("GODREJAGRO", "Godrej Agrovet"),
    ("TCIEXP", "TCI Express"),
    ("BLUEDART", "Blue Dart Express"),
    ("ALLCARGO", "Allcargo Logistics"),
    ("VRL", "VRL Logistics"),
    ("REDINGTON", "Redington"),
    ("CENTURYPLY", "Century Plyboards"),
    ("GREENPLY", "Greenply Industries"),
    ("JKPAPER", "JK Paper"),
    ("STLTECH", "Sterlite Technologies"),
    ("TEJAS", "Tejas Networks"),
    ("MTNL", "Mahanagar Telephone Nigam"),
    ("TEAMLEASE", "TeamLease Services"),
    ("QUESS", "Quess Corp"),
    ("SIS", "SIS Limited"),
    ("GREAVESCOT", "Greaves Cotton"),
    ("BOROSIL", "Borosil Renewables"),
    ("PCJEWELLER", "PC Jeweller"),
    ("JPASSOCIAT", "Jaiprakash Associates"),
]

# Pre-built list of dicts for API responses (with .NS suffix)
NSE_STOCK_LIST = [
    {"symbol": f"{sym}.NS", "name": name, "exchange": "NSE"} for sym, name in NSE_STOCKS
]
