"""
AlphaSync Signal Generator — Smart strategy rule evaluation.

Each strategy uses MULTI-INDICATOR CONFIRMATION to avoid false signals.
A single indicator crossover is not enough — we require alignment from
at least 2-3 indicators before generating a BUY/SELL signal.

Strategies:
    SMA_CROSSOVER  — Golden/death cross + RSI + volume confirmation
    RSI            — Oversold/overbought + EMA trend filter + MACD confirm
    MACD           — Signal crossover + histogram momentum + RSI confirm
    BOLLINGER      — Band touch + RSI divergence + trend filter
    EMA_CROSSOVER  — Fast/slow EMA cross + MACD + volume surge
    VWAP_BOUNCE    — VWAP support/resistance + RSI + volume confirm

Usage:
    from engines.signals import signal_generator, Signal
    signal = signal_generator.evaluate("SMA_CROSSOVER", indicators)
"""

import logging
from dataclasses import dataclass
from typing import Optional
from engines.indicators import IndicatorEngine

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy evaluation."""
    action: str  # "BUY", "SELL", "HOLD"
    confidence: float = 0.0  # 0.0 to 1.0
    reason: str = ""
    indicator_values: dict = None

    def __post_init__(self):
        if self.indicator_values is None:
            self.indicator_values = {}


class SignalGenerator:
    """
    Smart signal generator with multi-indicator confirmation.

    Key principles:
    1. Never trade on a single indicator — require 2-3 confirmations
    2. Dynamic confidence based on how many confirmations align
    3. Volume must confirm the move (no low-volume signals)
    4. Trend filter prevents counter-trend entries
    """

    def evaluate(
        self,
        strategy_type: str,
        closes: list[float],
        highs: list[float] = None,
        lows: list[float] = None,
        volumes: list[int] = None,
        parameters: dict = None,
    ) -> Signal:
        params = parameters or {}

        match strategy_type:
            case "SMA_CROSSOVER":
                return self._sma_crossover(closes, highs, lows, volumes, params)
            case "RSI":
                return self._rsi_strategy(closes, highs, lows, volumes, params)
            case "MACD":
                return self._macd_strategy(closes, highs, lows, volumes, params)
            case "BOLLINGER":
                return self._bollinger_strategy(closes, highs, lows, volumes, params)
            case "EMA_CROSSOVER":
                return self._ema_crossover(closes, highs, lows, volumes, params)
            case "VWAP_BOUNCE":
                return self._vwap_bounce(closes, highs, lows, volumes, params)
            case _:
                logger.warning(f"Unknown strategy type: {strategy_type}")
                return Signal(action="HOLD", reason=f"Unknown strategy: {strategy_type}")

    # ── Helper: compute common indicators ─────────────────────────────────────

    def _compute_common(self, closes, volumes=None):
        """Compute commonly used indicators for confirmation checks."""
        rsi_vals = IndicatorEngine.rsi(closes, 14)
        rsi = rsi_vals[-1] if rsi_vals else None

        macd_result = IndicatorEngine.macd(closes)
        macd_hist = None
        macd_prev_hist = None
        if macd_result:
            valid = [h for h in macd_result.histogram if h is not None]
            if len(valid) >= 2:
                macd_hist = valid[-1]
                macd_prev_hist = valid[-2]

        vol_ratio = None
        if volumes and len(volumes) >= 20:
            avg_vol = sum(volumes[-20:]) / 20
            if avg_vol > 0:
                vol_ratio = volumes[-1] / avg_vol

        ema_20 = IndicatorEngine.ema(closes, 20)
        ema_50 = IndicatorEngine.ema(closes, 50) if len(closes) >= 55 else None

        return {
            "rsi": rsi,
            "macd_hist": macd_hist,
            "macd_prev_hist": macd_prev_hist,
            "vol_ratio": round(vol_ratio, 2) if vol_ratio else None,
            "ema_20": ema_20[-1] if ema_20 and ema_20[-1] is not None else None,
            "ema_50": ema_50[-1] if ema_50 and ema_50[-1] is not None else None,
            "price": closes[-1],
        }

    # ── SMA Crossover + Multi-Indicator ────────────────────────────────────────

    def _sma_crossover(self, closes, highs, lows, volumes, params) -> Signal:
        """
        SMA Crossover with RSI + volume confirmation.

        BUY:  Golden cross + RSI not overbought + volume above average
        SELL: Death cross + RSI not oversold + volume above average
        """
        short_period = params.get("short_period", 10)
        long_period = params.get("long_period", 20)

        if len(closes) < max(long_period + 2, 55):
            return Signal(action="HOLD", reason="Insufficient data for SMA crossover")

        short_sma = IndicatorEngine.sma(closes, short_period)
        long_sma = IndicatorEngine.sma(closes, long_period)

        curr_short, prev_short = short_sma[-1], short_sma[-2]
        curr_long, prev_long = long_sma[-1], long_sma[-2]

        if any(v is None for v in [curr_short, prev_short, curr_long, prev_long]):
            return Signal(action="HOLD", reason="Insufficient indicator data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "short_sma": curr_short, "long_sma": curr_long,
            "rsi": common["rsi"], "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        # Golden cross: short crosses above long
        if prev_short <= prev_long and curr_short > curr_long:
            confirmations = 0
            reasons = ["SMA golden cross detected"]

            # Confirmation 1: RSI is in bullish zone (not overbought)
            if common["rsi"] and 35 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms (bullish zone)")
            elif common["rsi"] and common["rsi"] > 70:
                reasons.append(f"RSI {common['rsi']:.0f} overbought — weak signal")

            # Confirmation 2: MACD histogram positive or turning positive
            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD histogram positive")

            # Confirmation 3: Volume above average
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)

            if confirmations >= 1:
                return Signal(
                    action="BUY", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals,
                )
            return Signal(action="HOLD", reason="Golden cross but no confirmations", indicator_values=indicator_vals)

        # Death cross: short crosses below long
        if prev_short >= prev_long and curr_short < curr_long:
            confirmations = 0
            reasons = ["SMA death cross detected"]

            if common["rsi"] and 30 <= common["rsi"] <= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms (bearish zone)")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD histogram negative")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)

            if confirmations >= 1:
                return Signal(
                    action="SELL", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals,
                )
            return Signal(action="HOLD", reason="Death cross but no confirmations", indicator_values=indicator_vals)

        return Signal(action="HOLD", reason="No SMA crossover", indicator_values=indicator_vals)

    # ── RSI Strategy + Trend Filter ────────────────────────────────────────────

    def _rsi_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        RSI with EMA trend filter + MACD momentum confirmation.

        BUY:  RSI bounces from oversold + price above EMA-50 (uptrend) + MACD turning
        SELL: RSI enters overbought + price below EMA-50 (downtrend) + MACD turning
        """
        period = params.get("period", 14)
        oversold = params.get("oversold", 30)
        overbought = params.get("overbought", 70)

        if len(closes) < max(period + 3, 55):
            return Signal(action="HOLD", reason="Insufficient data for RSI")

        rsi_values = IndicatorEngine.rsi(closes, period)
        curr_rsi = rsi_values[-1]
        prev_rsi = rsi_values[-2] if len(rsi_values) >= 2 else None

        if curr_rsi is None or prev_rsi is None:
            return Signal(action="HOLD", reason="Insufficient RSI data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "rsi": curr_rsi, "prev_rsi": prev_rsi,
            "ema_20": common["ema_20"], "ema_50": common["ema_50"],
            "macd_hist": common["macd_hist"], "vol_ratio": common["vol_ratio"],
        }

        # BUY: RSI crosses up from oversold zone
        if prev_rsi <= oversold and curr_rsi > oversold:
            confirmations = 0
            reasons = [f"RSI bounced from oversold ({prev_rsi:.0f} → {curr_rsi:.0f})"]

            # Confirmation 1: Price above EMA-50 (in an uptrend)
            if common["ema_50"] and closes[-1] > common["ema_50"]:
                confirmations += 1
                reasons.append("Price above EMA-50 (uptrend)")
            elif common["ema_20"] and closes[-1] > common["ema_20"]:
                confirmations += 1
                reasons.append("Price above EMA-20 (short-term uptrend)")

            # Confirmation 2: MACD histogram turning positive
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning bullish")

            # Confirmation 3: Volume surge
            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            return Signal(
                action="BUY", confidence=confidence,
                reason=" | ".join(reasons), indicator_values=indicator_vals,
            )

        # SELL: RSI crosses into overbought zone
        if prev_rsi < overbought and curr_rsi >= overbought:
            confirmations = 0
            reasons = [f"RSI entered overbought ({prev_rsi:.0f} → {curr_rsi:.0f})"]

            if common["ema_50"] and closes[-1] < common["ema_50"]:
                confirmations += 1
                reasons.append("Price below EMA-50 (downtrend)")
            elif common["ema_20"] and closes[-1] < common["ema_20"]:
                confirmations += 1
                reasons.append("Price below EMA-20")

            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning bearish")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            return Signal(
                action="SELL", confidence=confidence,
                reason=" | ".join(reasons), indicator_values=indicator_vals,
            )

        # Also trigger on RSI staying deeply oversold/overbought (momentum extreme)
        if curr_rsi <= oversold - 5:
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:  # momentum turning
                    return Signal(
                        action="BUY", confidence=0.6,
                        reason=f"RSI deeply oversold ({curr_rsi:.0f}) + MACD turning up",
                        indicator_values=indicator_vals,
                    )

        if curr_rsi >= overbought + 5:
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    return Signal(
                        action="SELL", confidence=0.6,
                        reason=f"RSI extremely overbought ({curr_rsi:.0f}) + MACD turning down",
                        indicator_values=indicator_vals,
                    )

        return Signal(action="HOLD", reason=f"RSI at {curr_rsi:.0f} — no signal", indicator_values=indicator_vals)

    # ── MACD Strategy + Momentum + RSI ─────────────────────────────────────────

    def _macd_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        MACD signal crossover + histogram momentum + RSI confirmation.

        BUY:  MACD crosses above signal + histogram growing + RSI not overbought
        SELL: MACD crosses below signal + histogram growing + RSI not oversold
        """
        fast = params.get("fast_period", 12)
        slow = params.get("slow_period", 26)
        signal_period = params.get("signal_period", 9)

        macd_result = IndicatorEngine.macd(closes, fast, slow, signal_period)
        if macd_result is None:
            return Signal(action="HOLD", reason="Insufficient data for MACD")

        macd_line = macd_result.macd_line
        signal_line = macd_result.signal_line
        histogram = macd_result.histogram

        curr_macd, prev_macd = macd_line[-1], macd_line[-2]
        curr_signal, prev_signal = signal_line[-1], signal_line[-2]

        if any(v is None for v in [curr_macd, prev_macd, curr_signal, prev_signal]):
            return Signal(action="HOLD", reason="Insufficient MACD data")

        # Get histogram momentum (growing vs fading)
        valid_hist = [h for h in histogram if h is not None]
        hist_growing = False
        if len(valid_hist) >= 2:
            hist_growing = abs(valid_hist[-1]) > abs(valid_hist[-2])

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "macd": curr_macd, "signal": curr_signal,
            "histogram": valid_hist[-1] if valid_hist else None,
            "hist_growing": hist_growing,
            "rsi": common["rsi"], "vol_ratio": common["vol_ratio"],
        }

        # Bullish crossover
        if prev_macd <= prev_signal and curr_macd > curr_signal:
            confirmations = 0
            reasons = ["MACD bullish crossover"]

            # Confirmation 1: Histogram growing (momentum accelerating)
            if hist_growing and valid_hist[-1] > 0:
                confirmations += 1
                reasons.append("Histogram growing — strong momentum")

            # Confirmation 2: RSI in bullish zone
            if common["rsi"] and 30 <= common["rsi"] <= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms bullish")

            # Confirmation 3: Crossover above zero line (stronger signal)
            if curr_macd > 0:
                confirmations += 1
                reasons.append("Crossover above zero line — strong")

            # Confirmation 4: Volume
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.45 + confirmations * 0.12, 0.95)
            return Signal(
                action="BUY", confidence=confidence,
                reason=" | ".join(reasons), indicator_values=indicator_vals,
            )

        # Bearish crossover
        if prev_macd >= prev_signal and curr_macd < curr_signal:
            confirmations = 0
            reasons = ["MACD bearish crossover"]

            if hist_growing and valid_hist[-1] < 0:
                confirmations += 1
                reasons.append("Histogram growing negative — strong bearish")

            if common["rsi"] and 35 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms bearish")

            if curr_macd < 0:
                confirmations += 1
                reasons.append("Crossover below zero line — strong")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.45 + confirmations * 0.12, 0.95)
            return Signal(
                action="SELL", confidence=confidence,
                reason=" | ".join(reasons), indicator_values=indicator_vals,
            )

        return Signal(action="HOLD", reason="No MACD crossover", indicator_values=indicator_vals)

    # ── Bollinger Bands + RSI + Trend ──────────────────────────────────────────

    def _bollinger_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Bollinger Bands mean reversion with RSI + trend filter.

        BUY:  Price at lower band + RSI oversold + NOT in strong downtrend
        SELL: Price at upper band + RSI overbought + NOT in strong uptrend
        """
        period = params.get("period", 20)
        std_dev = params.get("std_dev", 2.0)

        if len(closes) < max(period, 55):
            return Signal(action="HOLD", reason="Insufficient data for Bollinger")

        bb_result = IndicatorEngine.bollinger_bands(closes, period, std_dev)
        if bb_result is None:
            return Signal(action="HOLD", reason="Insufficient Bollinger data")

        curr_price = closes[-1]
        curr_upper = bb_result.upper[-1]
        curr_lower = bb_result.lower[-1]
        curr_middle = bb_result.middle[-1]

        if any(v is None for v in [curr_upper, curr_lower, curr_middle]):
            return Signal(action="HOLD", reason="Insufficient Bollinger data")

        common = self._compute_common(closes, volumes)

        # Calculate %B (position within bands)
        band_width = curr_upper - curr_lower
        pct_b = (curr_price - curr_lower) / band_width if band_width > 0 else 0.5

        indicator_vals = {
            "price": curr_price, "upper": curr_upper,
            "middle": curr_middle, "lower": curr_lower,
            "pct_b": round(pct_b, 3), "rsi": common["rsi"],
            "ema_50": common["ema_50"], "vol_ratio": common["vol_ratio"],
        }

        # BUY: Price at or below lower band
        if curr_price <= curr_lower:
            confirmations = 0
            reasons = [f"Price at lower BB (₹{curr_price:.0f} ≤ ₹{curr_lower:.0f})"]

            # Confirmation 1: RSI confirms oversold
            if common["rsi"] and common["rsi"] <= 35:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} oversold")

            # Confirmation 2: NOT in a strong downtrend (don't catch falling knives)
            if common["ema_50"] and curr_price > common["ema_50"] * 0.97:
                confirmations += 1
                reasons.append("Not in strong downtrend (price near EMA-50)")
            elif common["ema_20"] and curr_price > common["ema_20"] * 0.98:
                confirmations += 1
                reasons.append("Price near EMA-20 — potential bounce")

            # Confirmation 3: Volume spike (capitulation / accumulation)
            if common["vol_ratio"] and common["vol_ratio"] >= 1.5:
                confirmations += 1
                reasons.append(f"Volume spike {common['vol_ratio']:.1f}x — potential capitulation")

            # Confirmation 4: MACD turning up
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning up")

            if confirmations >= 1:
                confidence = min(0.45 + confirmations * 0.12, 0.90)
                return Signal(
                    action="BUY", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals,
                )
            return Signal(action="HOLD", reason="Lower BB touch but no confirmations", indicator_values=indicator_vals)

        # SELL: Price at or above upper band
        if curr_price >= curr_upper:
            confirmations = 0
            reasons = [f"Price at upper BB (₹{curr_price:.0f} ≥ ₹{curr_upper:.0f})"]

            if common["rsi"] and common["rsi"] >= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} overbought")

            if common["ema_50"] and curr_price < common["ema_50"] * 1.03:
                confirmations += 1
                reasons.append("Not in strong uptrend")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.5:
                confirmations += 1
                reasons.append(f"Volume spike {common['vol_ratio']:.1f}x — distribution")

            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum fading")

            if confirmations >= 1:
                confidence = min(0.45 + confirmations * 0.12, 0.90)
                return Signal(
                    action="SELL", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals,
                )
            return Signal(action="HOLD", reason="Upper BB touch but no confirmations", indicator_values=indicator_vals)

        return Signal(
            action="HOLD",
            reason=f"Price within bands (%B: {pct_b:.1%})",
            indicator_values=indicator_vals,
        )

    # ── EMA Crossover (NEW) ────────────────────────────────────────────────────

    def _ema_crossover(self, closes, highs, lows, volumes, params) -> Signal:
        """
        EMA Crossover — faster than SMA, better for trending markets.

        BUY:  Fast EMA crosses above slow EMA + MACD positive + volume surge
        SELL: Fast EMA crosses below slow EMA + MACD negative + volume surge
        """
        fast_period = params.get("fast_period", 9)
        slow_period = params.get("slow_period", 21)

        if len(closes) < max(slow_period + 2, 55):
            return Signal(action="HOLD", reason="Insufficient data for EMA crossover")

        fast_ema = IndicatorEngine.ema(closes, fast_period)
        slow_ema = IndicatorEngine.ema(closes, slow_period)

        curr_fast, prev_fast = fast_ema[-1], fast_ema[-2]
        curr_slow, prev_slow = slow_ema[-1], slow_ema[-2]

        if any(v is None for v in [curr_fast, prev_fast, curr_slow, prev_slow]):
            return Signal(action="HOLD", reason="Insufficient EMA data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "fast_ema": curr_fast, "slow_ema": curr_slow,
            "spread_pct": round((curr_fast - curr_slow) / curr_slow * 100, 3) if curr_slow else 0,
            "rsi": common["rsi"], "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        # Bullish EMA crossover
        if prev_fast <= prev_slow and curr_fast > curr_slow:
            confirmations = 0
            reasons = [f"EMA({fast_period}) crossed above EMA({slow_period})"]

            if common["rsi"] and 40 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} bullish")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD positive")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(action="BUY", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals)

        # Bearish EMA crossover
        if prev_fast >= prev_slow and curr_fast < curr_slow:
            confirmations = 0
            reasons = [f"EMA({fast_period}) crossed below EMA({slow_period})"]

            if common["rsi"] and 30 <= common["rsi"] <= 60:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} bearish")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD negative")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(action="SELL", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals)

        return Signal(action="HOLD", reason="No EMA crossover", indicator_values=indicator_vals)

    # ── VWAP Bounce (NEW) ──────────────────────────────────────────────────────

    def _vwap_bounce(self, closes, highs, lows, volumes, params) -> Signal:
        """
        VWAP Support/Resistance bounce — best for intraday.

        BUY:  Price bounces off VWAP support + RSI confirms + volume confirms
        SELL: Price rejected at VWAP resistance + RSI confirms + volume confirms
        """
        if not highs or not lows or not volumes:
            return Signal(action="HOLD", reason="Need OHLCV data for VWAP")

        if len(closes) < 30:
            return Signal(action="HOLD", reason="Insufficient data for VWAP")

        vwap_vals = IndicatorEngine.vwap(highs, lows, closes, volumes)
        if not vwap_vals or vwap_vals[-1] is None:
            return Signal(action="HOLD", reason="VWAP calculation failed")

        curr_vwap = vwap_vals[-1]
        curr_price = closes[-1]
        prev_price = closes[-2]

        # Price distance from VWAP as percentage
        vwap_dist_pct = (curr_price - curr_vwap) / curr_vwap * 100 if curr_vwap else 0

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "price": curr_price, "vwap": curr_vwap,
            "vwap_dist_pct": round(vwap_dist_pct, 3),
            "rsi": common["rsi"], "vol_ratio": common["vol_ratio"],
        }

        # BUY: Price bounces UP from near/below VWAP
        if prev_price <= curr_vwap * 1.002 and curr_price > curr_vwap:
            confirmations = 0
            reasons = [f"Price bounced above VWAP (₹{curr_vwap:.0f})"]

            if common["rsi"] and common["rsi"] <= 55:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not overbought")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD positive")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.12, 0.90)
                return Signal(action="BUY", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals)

        # SELL: Price rejected DOWN from near/above VWAP
        if prev_price >= curr_vwap * 0.998 and curr_price < curr_vwap:
            confirmations = 0
            reasons = [f"Price rejected below VWAP (₹{curr_vwap:.0f})"]

            if common["rsi"] and common["rsi"] >= 45:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not oversold")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD negative")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.12, 0.90)
                return Signal(action="SELL", confidence=confidence,
                    reason=" | ".join(reasons), indicator_values=indicator_vals)

        return Signal(action="HOLD", reason=f"Price {vwap_dist_pct:+.1f}% from VWAP — no signal",
            indicator_values=indicator_vals)


# ── Singleton ─────────────────────────────────────────────────────
signal_generator = SignalGenerator()
